%Set training options and create a newly trained YOLO object detector
options = trainingOptions('sgdm',...
          'InitialLearnRate',0.001,...
          'Verbose',true,...
          'MiniBatchSize',8,...
          'MaxEpochs',60,...
          'Shuffle','never',...
          'VerboseFrequency',30,...
          'CheckpointPath',tempdir,'ExecutionEnvironment','cpu');
[detector,info] = trainYOLOv2ObjectDetector(preprocessedTrainingData,lgraph,options);

